import { RotateCcw, Mail } from 'lucide-react';
import { useState } from 'react';
import MovieCard from './MovieCard';

export default function RecommendationResults({ recommendations, onRestart }) {
  const [showEmailForm, setShowEmailForm] = useState(false);
  const [email, setEmail] = useState('');
  const [isSending, setIsSending] = useState(false);

  const formatEmailBody = () => {
    let body = "MY PERSONALIZED MOVIE RECOMMENDATIONS\n\n";
    recommendations.forEach((movie, index) => {
      body += `${index + 1}. ${movie.title} (${movie.release_date?.substring(0, 4) || 'N/A'})\n`;
      body += `   ★ Rating: ${movie.vote_average}/10\n`;
      body += `   ● Match: ${movie.similarity_score?.toFixed(0)}%\n`;
      if (movie.overview) {
        body += `   ${movie.overview.substring(0, 120)}...\n`;
      }
      body += '\n';
    });
    body += "Generated by Movie Recommender\nVisit: [Your Website URL]\n";
    return encodeURIComponent(body);
  };

  const handleEmailClick = () => {
    if (email) {
      setIsSending(true);
      const subject = encodeURIComponent("My Personalized Movie Recommendations");
      const body = formatEmailBody();
      
      const mailtoLink = `mailto:${email}?subject=${subject}&body=${body}`;
      window.location.href = mailtoLink;
      
      setTimeout(() => {
        setIsSending(false);
        setShowEmailForm(false);
      }, 1000);
    }
  };

  return (
    <div style={{ 
      minHeight: '100vh', 
      background: 'linear-gradient(to bottom right, #0f172a, #581c87, #0f172a)',
      padding: '2rem 1rem',
      overflowX: 'hidden'
    }}>
      <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
        
        <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
          <div style={{ 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'center', 
            gap: '0.75rem',
            marginBottom: '1rem'
          }}>
            <h1 style={{ fontSize: '2.5rem', fontWeight: 'bold', color: 'white', margin: 0 }}>
              Your Perfect Matches
            </h1>
          </div>
          <p style={{ fontSize: '1.2rem', color: '#d1d5db' }}>
            Based on your selections, we found these movies for you!
          </p>
        </div>

        <div style={{ 
          textAlign: 'center', 
          marginBottom: '3rem',
          display: 'flex',
          gap: '1rem',
          justifyContent: 'center',
          flexWrap: 'wrap'
        }}>
          <button
            onClick={onRestart}
            style={{
              background: '#1e293b',
              color: 'white',
              fontWeight: 'bold',
              padding: '0.875rem 1.5rem',
              borderRadius: '0.75rem',
              fontSize: '1rem',
              border: '1px solid #334155',
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              transition: 'all 0.2s'
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = '#334155';
              e.currentTarget.style.transform = 'scale(1.05)';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = '#1e293b';
              e.currentTarget.style.transform = 'scale(1)';
            }}
          >
            <RotateCcw size={20} />
            Start Over
          </button>

          <button
            onClick={() => setShowEmailForm(!showEmailForm)}
            style={{
              background: 'linear-gradient(to right, #9333ea, #4850ecff)',
              color: 'white',
              fontWeight: 'bold',
              padding: '0.875rem 1.5rem',
              borderRadius: '0.75rem',
              fontSize: '1rem',
              border: 'none',
              cursor: 'pointer',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.5rem',
              transition: 'all 0.2s',
              boxShadow: '0 4px 15px rgba(147, 51, 234, 0.4)'
            }}
            onMouseEnter={(e) => e.currentTarget.style.transform = 'scale(1.05)'}
            onMouseLeave={(e) => e.currentTarget.style.transform = 'scale(1)'}
          >
            <Mail size={20} />
            Email Results
          </button>
        </div>

        {showEmailForm && (
          <div style={{
            maxWidth: '500px',
            margin: '0 auto 2rem auto',
            padding: '1.5rem',
            background: '#1e293b',
            borderRadius: '1rem',
            border: '1px solid #334155',
            animation: 'slideDown 0.3s ease'
          }}>
            <h3 style={{ color: 'white', marginBottom: '1rem', fontSize: '1.1rem' }}>
              📧 Email Your Recommendations
            </h3>
            <p style={{ color: '#9ca3af', fontSize: '0.875rem', marginBottom: '1rem' }}>
              This will open your email client with a pre-filled message
            </p>
            <input
              type="email"
              placeholder="Enter your email address"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              style={{
                width: '100%',
                padding: '0.75rem',
                background: '#0f172a',
                color: 'white',
                border: '1px solid #334155',
                borderRadius: '0.5rem',
                fontSize: '1rem',
                marginBottom: '1rem',
                outline: 'none',
                boxSizing: 'border-box'
              }}
              onKeyPress={(e) => {
                if (e.key === 'Enter') handleEmailClick();
              }}
            />
            <button
              onClick={handleEmailClick}
              disabled={!email || isSending}
              style={{
                width: '100%',
                background: email ? 'linear-gradient(to right, #9333ea, #4850ecff)' : '#334155',
                color: 'white',
                fontWeight: 'bold',
                padding: '0.75rem',
                borderRadius: '0.5rem',
                fontSize: '1rem',
                border: 'none',
                cursor: email ? 'pointer' : 'not-allowed',
                transition: 'all 0.2s'
              }}
            >
              {isSending ? 'Opening Email...' : 'Send to My Email'}
            </button>
          </div>
        )}

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
          gap: '2rem',
          padding: '0 1rem'
        }}>
          {recommendations.map((movie, index) => (
            <div
              key={movie.id}
              style={{
                animation: 'fadeIn 0.5s ease-in',
                position: 'relative'
              }}
            >
              {index < 3 && (
                <div style={{
                  position: 'absolute',
                  top: '-0.5rem',
                  left: '-0.5rem',
                  background: index === 0 ? 'linear-gradient(135deg, #fbbf24, #f59e0b)' : index === 1 ? 'linear-gradient(135deg, #d1d5db, #9ca3af)' : 'linear-gradient(135deg, #fb923c, #ea580c)',
                  color: 'white',
                  fontWeight: 'bold',
                  fontSize: '0.75rem',
                  padding: '0.25rem 0.5rem',
                  borderRadius: '9999px',
                  zIndex: 10,
                  boxShadow: '0 2px 8px rgba(0, 0, 0, 0.3)',
                  border: '2px solid white'
                }}>
                  {index === 0 ? '#1' : index === 1 ? '#2' : '#3'}
                </div>
              )}
              <MovieCard
                movie={movie}
                isSelected={false}
                showScore={true}
              />
            </div>
          ))}
        </div>
      </div>

      <style>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        
        @keyframes slideDown {
          from {
            opacity: 0;
            transform: translateY(-10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      `}</style>
    </div>
  );
}